// Code generated by go generate; DO NOT EDIT.
// To recreate run: make generate
// 2023-01-27 22:01:03.706648 +0100 CET m=+0.003635126
package server

const (
	// Get command
	Get = "GET"
	// Set command
	Set = "SET"
	// Incr command
	Incr = "INCR"
	// IncrBy command
	IncrBy = "INCRBY"
	// Decr command
	Decr = "DECR"
	// DecrBy command
	DecrBy = "DECRBY"
	// Substr command
	Substr = "SUBSTR"
	// MGet command
	MGet = "MGET"
	// Echo command
	Echo = "ECHO"
	// Ping command
	Ping = "PING"
	// Quit command
	Quit = "QUIT"
	// Select command
	Select = "SELECT"
	// Auth command
	Auth = "AUTH"
	// Del command
	Del = "DEL"
	// Exists command
	Exists = "EXISTS"
	// Move command
	Move = "MOVE"
	// RandomKey command
	RandomKey = "RANDOMKEY"
	// Rename command
	Rename = "RENAME"
	// Expire command
	Expire = "EXPIRE"
	// TTL command
	TTL = "TTL"
	// DBSize command
	DBSize = "DBSIZE"
	// FlushDB command
	FlushDB = "FLUSHDB"
	// FlushAll command
	FlushAll = "FLUSHALL"
	// Config command
	Config = "CONFIG"
	// SetNX command
	SetNX = "SETNX"
	// LLen command
	LLen = "LLEN"
	// LRange command
	LRange = "LRANGE"
	// LRem command
	LRem = "LREM"
	// LIndex command
	LIndex = "LINDEX"
	// LSet command
	LSet = "LSET"
	// LPush command
	LPush = "LPUSH"
	// RPush command
	RPush = "RPUSH"
	// LPop command
	LPop = "LPOP"
	// RPop command
	RPop = "RPOP"
	// LTrim command
	LTrim = "LTRIM"
)
